In [ ]:
import numpy as np

In [ ]:
def to_scale_rand(lower,upper,n=10):
  ins=np.random.randint(2,size=n)
  outs=(upper-lower)*ins+lower
  return(outs)

to_scale_rand(10,100)

array([ 10,  10, 100,  10,  10, 100, 100, 100, 100,  10])

In [ ]:
# Number of desired iterations
N=10**4

# only about 1/6 of random conditions satisfy reasonability requirements
N=N

# All values have min 0, adjust values below to change upper bound

#nu=to_scale_rand(8,5,N)
nd=10*np.random.beta(2,3,N)
z=2*rbeta(10000,2,5)
#nd=to_scale_rand(4,0,N)
nu=(z+1)*nd
A=to_scale_rand(0,100,N)
beta=to_scale_rand(.95,.75,N)
delta=to_scale_rand(.25,1,N)
Iu=to_scale_rand(75,35,N)
Id=to_scale_rand(25,0,N)
I0=to_scale_rand(50,75,N)

inputs = np.stack([nu,nd,A,beta,delta,Iu,Id,I0],axis=1)
inputs.shape

NameError: ignored

In [ ]:
# Create expected utility at parameters

def compute_U(input_row):
  nu,nd,A,beta,delta,Iu,Id,I0=input_row
  Q=(1-delta)*A+I0 #constant to make formulas shorter
  # Compute utilities
  uA=(Q+I0)*nd+beta*((1-delta)*(Q+I0)+2*Id)*nd
  uB=(Q)*nu+beta*((1-delta)*(Q)+2*Iu)*nd
  uC=(Q+I0)*nd+beta*((1-delta)*(Q+I0)+Id)*nu
  uD=(Q)*nu+beta*((1-delta)*Q+Iu)*nu

  #return each utility
  return [uA, uB, uC, uD]

#compute utility for each strategy at every input
U=np.apply_along_axis(compute_U,1,inputs) 
U.shape

(10000, 4)

In [ ]:
def rank(LETTERS): #function to define a potential ranking of outcomes
  # accepts a vector [n1,n2,n3,n4] giving which is preferred to which
  TruthTable= \
  (U[:,LETTERS[0]]>U[:,LETTERS[1]])& \
  (U[:,LETTERS[1]]>U[:,LETTERS[2]])& \
  (U[:,LETTERS[2]]>U[:,LETTERS[3]])
  #returns a Nx1 vector of whether or not the proposed ranking is true for the set of inputs
  return TruthTable

import itertools
#makes all permutations, which is all possible rankings
LETTERS=np.array(list(itertools.permutations([0,1,2,3]))) 

In [ ]:
# for each possible ranking compute when that's possible
OUT=np.apply_along_axis(rank,1,LETTERS)

In [ ]:
# see which rankings occur a non-zero amount of times
#STRATS=np.array(list(itertools.permutations(["low,low>","high,low>","low,high>","high,high>"]))) 
STRATS=np.array(list(itertools.permutations(["A","B","C","D"]))) 
Outcome=np.append(STRATS,np.apply_along_axis(np.count_nonzero,1,OUT).reshape(-1,1),axis=1)
print(Outcome)

[['A' 'B' 'C' 'D' '0']
 ['A' 'B' 'D' 'C' '0']
 ['A' 'C' 'B' 'D' '325']
 ['A' 'C' 'D' 'B' '0']
 ['A' 'D' 'B' 'C' '0']
 ['A' 'D' 'C' 'B' '0']
 ['B' 'A' 'C' 'D' '83']
 ['B' 'A' 'D' 'C' '168']
 ['B' 'C' 'A' 'D' '32']
 ['B' 'C' 'D' 'A' '168']
 ['B' 'D' 'A' 'C' '81']
 ['B' 'D' 'C' 'A' '110']
 ['C' 'A' 'B' 'D' '450']
 ['C' 'A' 'D' 'B' '145']
 ['C' 'B' 'A' 'D' '74']
 ['C' 'B' 'D' 'A' '86']
 ['C' 'D' 'A' 'B' '168']
 ['C' 'D' 'B' 'A' '252']
 ['D' 'A' 'B' 'C' '0']
 ['D' 'A' 'C' 'B' '0']
 ['D' 'B' 'A' 'C' '0']
 ['D' 'B' 'C' 'A' '2357']
 ['D' 'C' 'A' 'B' '0']
 ['D' 'C' 'B' 'A' '2140']]


In [ ]:
# add input data
out_data=np.append(inputs,OUT.T,axis=1)
A_win=np.sum(OUT.T[:,0:6],axis=1)
B_win=np.sum(OUT.T[:,6:12],axis=1)
C_win=np.sum(OUT.T[:,12:18],axis=1)
D_win=np.sum(OUT.T[:,18:24],axis=1)

In [ ]:
OUT.shape

(24, 10000)

# Sensitivity Analysis
At this point, we know which strategy is preferred ex ante. We should take their ex ante strategy, apply their optimal period one behavior, add a production shock (the algorithm) and see how the size of the shock changes their strategy.

We can proceed similarly, but not identically. We right now have $4$ vectors that tell which strategy won for each simulation. I will extract the first period behavior $A$ and $C$ have low first periods. $B$ and $D$ have high first periods.

I will recall the parameters for this simulation, compute the deterministic component of audience, then add the shock.

We will then have a new audience size, and I will compare the high quality strategy to the low quality strategy.

In [ ]:
low_period_one = A_win+C_win
low_period_one = low_period_one.astype(np.bool)

factors=np.append(inputs,np.reshape(low_period_one,(-1,1)),axis=1)

# accepts a row vector of parameters including whether or not they choose 
# low strat period one
def shocks(factor_row,sigma=1):
  def shock_dist(sigma):
    return(np.random.normal(loc=0,scale=sigma))
  
  nu,nd,A,beta,delta,Iu,Id,I0,low=factor_row
  Q=(1-delta)*A+I0

  if low:
    total_shock=shock_dist(sigma)+shock_dist(sigma)
    aud=Q+I0+total_shock
    u_high = ((1-delta)*aud+Id)*nu # C
    u_low = ((1-delta)*aud+2*Id)*nd # A

    aud_det=Q+I0
    u_high_det = ((1-delta)*aud_det+Id)*nu #Not problematic
    u_low_det = ((1-delta)*aud_det+2*Id)*nd
  else :
    total_shock = shock_dist(sigma)
    aud=Q+total_shock
    u_high = ((1-delta)*aud+Iu)*nu # D
    u_low = ((1-delta)*aud+2*Iu)*nd # B

    aud_det=Q
    u_high_det = ((1-delta)*aud_det+Iu)*nu #Problematic (Q)*nu+beta*((1-delta)*Q+Iu)*nu
    u_low_det = ((1-delta)*aud_det+2*Iu)*nd

  return [u_high,u_low,aud,u_high_det,u_low_det,aud_det,total_shock]



In [ ]:
# Do this first to match output
shock_output_100=np.apply_along_axis(shocks,1,factors,sigma=100)
shock_output=shock_output_100

shock_output_0=np.apply_along_axis(shocks,1,factors,sigma=0) 
shock_output_1=np.apply_along_axis(shocks,1,factors,sigma=1) 
shock_output_2=np.apply_along_axis(shocks,1,factors,sigma=3.1622777) 
shock_output_3=np.apply_along_axis(shocks,1,factors,sigma=10) 
shock_output_4=np.apply_along_axis(shocks,1,factors,sigma=31.622777) 
 
shock_output_5=np.apply_along_axis(shocks,1,factors,sigma=316.22777) 
shock_output_6=np.apply_along_axis(shocks,1,factors,sigma=1000) 
shock_output_7=np.apply_along_axis(shocks,1,factors,sigma=3162.2777) 
shock_output_8=np.apply_along_axis(shocks,1,factors,sigma=10000)


#shock_output

In [ ]:
def format_shock_output(data,var):
  high_after_shock=data[:,0]>data[:,1]
  high_after_shock=np.reshape(high_after_shock,(-1,1))
  high_ex_ante=data[:,3]>data[:,4]
  high_ex_ante=np.reshape(high_ex_ante,(-1,1))

  diff=high_after_shock!=high_ex_ante

  compare=np.append(high_after_shock,high_ex_ante,axis=1)
  compare=np.append(compare,diff,axis=1)
  var_column=np.ones([compare.shape[0],1])*var
  compare=np.append(compare,var_column,axis=1)
  return compare

compare=format_shock_output(shock_output,100)
compare

array([[  0.,   0.,   0., 100.],
       [  0.,   0.,   0., 100.],
       [  0.,   0.,   0., 100.],
       ...,
       [  1.,   1.,   0., 100.],
       [  1.,   1.,   0., 100.],
       [  0.,   0.,   0., 100.]])

In [ ]:
format_shock_output(shock_output_100,100)

array([[  0.,   0.,   0., 100.],
       [  0.,   0.,   0., 100.],
       [  0.,   0.,   0., 100.],
       ...,
       [  1.,   1.,   0., 100.],
       [  1.,   1.,   0., 100.],
       [  0.,   0.,   0., 100.]])

In [ ]:
np.mean(compare[:,2])

0.0486

# Save output data

In [ ]:
import pandas as pd 
from google.colab import files

names=np.array(list(itertools.permutations(["A","B","C","D"])))
names=np.apply_along_axis(lambda d: d[0] + d[1] + d[2] + d[3], 1, names)
colnames=np.append(['nu','nd','iA','beta','delta','Iu','Id','I0'],names)

out_data=pd.DataFrame(out_data,columns=colnames)
out_data['A_win']=A_win
out_data['B_win']=B_win
out_data['C_win']=C_win
out_data['D_win']=D_win

def func(row):
    if row['A_win'] == 1:
        return "A"
    elif row['B_win'] ==1:
        return "B"
    elif row['C_win'] ==1:
        return "C"
    elif row['D_win'] ==1:
        return 'D'

out_data['winner'] = out_data.apply(func, axis=1)


out_data[['u_high','u_low','aud','u_high_det','u_low_det','aud_det','total_shock']]=pd.DataFrame(shock_output)


out_data[['high_after_shock','high_ex_ante','different','var']] = pd.DataFrame(compare)
out_data[['uA','uB','uC','uD']]=U


out_data.to_csv("SimulationDataWithShocks_Binary.csv")
files.download("SimulationDataWithShocks_Binary.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
out_data['winner'].unique()
#U

array([None, 'D', 'C', 'A', 'B'], dtype=object)

In [ ]:
#shock_output
LETTERS

array([[0, 1, 2, 3],
       [0, 1, 3, 2],
       [0, 2, 1, 3],
       [0, 2, 3, 1],
       [0, 3, 1, 2],
       [0, 3, 2, 1],
       [1, 0, 2, 3],
       [1, 0, 3, 2],
       [1, 2, 0, 3],
       [1, 2, 3, 0],
       [1, 3, 0, 2],
       [1, 3, 2, 0],
       [2, 0, 1, 3],
       [2, 0, 3, 1],
       [2, 1, 0, 3],
       [2, 1, 3, 0],
       [2, 3, 0, 1],
       [2, 3, 1, 0],
       [3, 0, 1, 2],
       [3, 0, 2, 1],
       [3, 1, 0, 2],
       [3, 1, 2, 0],
       [3, 2, 0, 1],
       [3, 2, 1, 0]])

# Varying Variance

In [ ]:
names=np.array(list(itertools.permutations(["A","B","C","D"])))
names=np.apply_along_axis(lambda d: d[0] + d[1] + d[2]+d[3] , 1, names)
colnames=np.append(['nu','nd','iA','beta','delta','Iu','Id','I0'],names)

out_data=pd.DataFrame(out_data,columns=colnames)
out_data['A_win']=A_win
out_data['B_win']=B_win
out_data['C_win']=C_win
out_data['D_win']=D_win

def func(row):
    if row['A_win'] == 1:
        return "A"
    elif row['B_win'] ==1:
        return "B"
    elif row['C_win'] ==1:
        return "C"
    elif row['D_win'] ==1:
        return 'D'

out_data['winner'] = out_data.apply(func, axis=1)
out_data[['uA','uB','uC','uD']]=U
out_data = pd.DataFrame(np.repeat(out_data.values, 10, axis=0),columns=out_data.columns)


# shock_output_0=np.apply_along_axis(shocks,1,factors,sigma=0) 
# shock_output_1=np.apply_along_axis(shocks,1,factors,sigma=1) 
# shock_output_2=np.apply_along_axis(shocks,1,factors,sigma=3.1622777) 
# shock_output_3=np.apply_along_axis(shocks,1,factors,sigma=10) 
# shock_output_4=np.apply_along_axis(shocks,1,factors,sigma=31.622777) 
 
# shock_output_5=np.apply_along_axis(shocks,1,factors,sigma=316.22777) 
# shock_output_6=np.apply_along_axis(shocks,1,factors,sigma=1000) 
# shock_output_7=np.apply_along_axis(shocks,1,factors,sigma=3162.2777) 
# shock_output_8=np.apply_along_axis(shocks,1,factors,sigma=10000)

compare_0=format_shock_output(shock_output_0,0)
compare_1=format_shock_output(shock_output_1,1)
compare_2=format_shock_output(shock_output_2,3.1622777)
compare_3=format_shock_output(shock_output_3,10)
compare_4=format_shock_output(shock_output_4,31.622777)
compare_5=format_shock_output(shock_output_5,316.22777)
compare_6=format_shock_output(shock_output_6,1000)
compare_7=format_shock_output(shock_output_7,3162.2777)
compare_8=format_shock_output(shock_output_8,10000)
compare_100=format_shock_output(shock_output_100,100)

big_compare=np.concatenate((compare_0,compare_1,compare_2,compare_3,compare_4,compare_5,compare_6,compare_7,compare_8,compare_100),axis=0)
big_shock_output=np.concatenate((shock_output_0,shock_output_1,shock_output_2,shock_output_3,shock_output_4,shock_output_5,shock_output_6,shock_output_7,shock_output_8,shock_output_100),axis=0)

out_data[['u_high','u_low','aud','u_high_det','u_low_det','aud_det','total_shock']]=pd.DataFrame(big_shock_output)


out_data[['high_after_shock','high_ex_ante','different','var']] = pd.DataFrame(big_compare)


out_data.to_csv("SimulationDataWithShocks_multiple_variance_Binary.csv")
files.download("SimulationDataWithShocks_multiple_variance_Binary.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
out_data.columns

Index(['nu', 'nd', 'iA', 'beta', 'delta', 'Iu', 'Id', 'I0', 'ABCD', 'ABDC',
       'ACBD', 'ACDB', 'ADBC', 'ADCB', 'BACD', 'BADC', 'BCAD', 'BCDA', 'BDAC',
       'BDCA', 'CABD', 'CADB', 'CBAD', 'CBDA', 'CDAB', 'CDBA', 'DABC', 'DACB',
       'DBAC', 'DBCA', 'DCAB', 'DCBA', 'A_win', 'B_win', 'C_win', 'D_win',
       'winner', 'uA', 'uB', 'uC', 'uD', 'u_high', 'u_low', 'aud',
       'u_high_det', 'u_low_det', 'aud_det', 'total_shock', 'high_after_shock',
       'high_ex_ante', 'different', 'var'],
      dtype='object')